# Generated by Django 2.2.6 on 2019-10-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operadora', models.CharField(choices=[('Oi', 'OI'), ('Tim', 'Tim'), ('Claro', 'Claro'), ('Vivo', 'Vivo')], max_length=20, verbose_name='Operadora')),
                ('plano', models.CharField(choices=[('Plano A', 'Plano A'), ('Plano B', 'Plano B'), ('Plano C', 'Plano C'), ('Plano D', 'Plano D')], max_length=20, verbose_name='Plano')),
            ],
        ),
    ]
